from enum import Enum

class ResponseSignal(Enum):
    FILE_VALIDATED_SUCCESS="FILE_VALIDATED_SUCCESS"
    FILE_TYPE_NOT_SUPPORTED = "FILE_TYPE_NOT_SUPPORTED"
    FILE_SIZE_EXCEEDED="FILE_SIZE_EXCEEDED"
    FILE_UPLOAD_SUCCESS="FILE_UPLOAD_SUCCESS"
    FILE_UPLOAD_FAILED="FILE_UPLOAD_FAILED"
    PROCESSING_FAILED= "processing_failed"
    PROCESSING_SUCESS="processing_success"